#AWS Deploy

version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore WarehouseTransport/WarehouseTransport.csproj
  build:
    commands: 
      - dotnet publish -c release -o WarehouseTransport/build_output WarehouseTransport/WarehouseTransport.csproj
artifacts:
  files:
    - WarehouseTransport/build_output/**/*
